# This is a basic workflow to help you get started with Actions

name: gradingWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-and-test:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - uses: actions/checkout@v3
      

      
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.9

      - name: Create Build Environment
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Debug

      - name: List files
        run: dir
            

      - name: Run with proper input
        run: .\build\Debug\*.exe TicTacToe < WintestA.txt > WintestAOutput.txt 
        shell: cmd

      - name: Display Student Output
        run: Get-Content WintestAOutput.txt
        

      


